version: "2.1"
services:
  mssql:
    container_name: mssql-dev
    hostname: mssql-dev
    build: .
    ports:
      - '1433:1433' # Map 1433 port of container to 1433 port of host to connect to outside services
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=p@ssw0rd
